[package]
name = "rs-jsonpath"
version = "1.0.0"
authors = ["freestrings <freestrings@gmail.com>"]

[dependencies]
log = "0.4"
env_logger = "0.6.0"
serde = "1.0"
serde_json = { version = "1.0", features = ["preserve_order"] }
indexmap = "1.0.2"

[dev-dependencies]
bencher = "0.1.5"
